# Generated by Django 5.2.6 on 2026-06-22 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='订单号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总额')),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('freight_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '待发货'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消'), ('refund', '退款中')], db_index=True, default='pending', max_length=20, verbose_name='订单状态')),
                ('receiver_name', models.CharField(default='', max_length=50, verbose_name='收货人')),
                ('receiver_phone', models.CharField(default='', max_length=11, verbose_name='收货电话')),
                ('receiver_address', models.CharField(default='', max_length=500, verbose_name='收货地址')),
                ('pay_method', models.CharField(blank=True, default='', max_length=20, verbose_name='支付方式')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('trade_no', models.CharField(blank=True, default='', max_length=100, verbose_name='交易流水号')),
                ('ship_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('express_no', models.CharField(blank=True, default='', max_length=100, verbose_name='快递单号')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.IntegerField()),
                ('spu_id', models.IntegerField()),
                ('goods_name', models.CharField(max_length=200)),
                ('goods_image', models.CharField(default='', max_length=500)),
                ('sku_name', models.CharField(default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
