# Generated by Django 6.0.6 on 2026-06-22 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='品牌名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='品牌Logo')),
                ('description', models.TextField(blank=True, default='', verbose_name='品牌描述')),
                ('first_letter', models.CharField(blank=True, default='', max_length=1, verbose_name='首字母')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'goods_brand',
                'ordering': ['-sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('level', models.SmallIntegerField(default=1, verbose_name='层级')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'goods_category',
                'ordering': ['-sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsSPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='商品名称')),
                ('subtitle', models.CharField(blank=True, default='', max_length=500, verbose_name='商品简介')),
                ('description', models.TextField(blank=True, default='', verbose_name='商品详情')),
                ('main_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='主图')),
                ('sales', models.IntegerField(default=0, verbose_name='总销量')),
                ('is_on_sale', models.BooleanField(db_index=True, default=False, verbose_name='上架状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标记')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spus', to='goods.brand', verbose_name='所属品牌')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spus', to='goods.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品SPU',
                'verbose_name_plural': '商品SPU',
                'db_table': 'goods_spu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='SKU名称')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='售价')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('specs', models.JSONField(blank=True, null=True, verbose_name='规格')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU图片')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认SKU')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='条形码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='goods.goodsspu', verbose_name='所属SPU')),
            ],
            options={
                'verbose_name': '商品SKU',
                'verbose_name_plural': '商品SKU',
                'db_table': 'goods_sku',
                'ordering': ['-is_default', 'price'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255, verbose_name='图片URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_main', models.BooleanField(default=False, verbose_name='主图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.goodsspu', verbose_name='所属SPU')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'goods_image',
                'ordering': ['-is_main', 'sort_order'],
            },
        ),
    ]
