# Generated by Django 5.2.6 on 2026-06-22 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsspu',
            name='seller',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'seller'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to=settings.AUTH_USER_MODEL, verbose_name='所属商家'),
        ),
    ]
