# Generated by Django 5.2.6 on 2026-06-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('seller', '商家')], default='user', max_length=10, verbose_name='用户角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_description',
            field=models.TextField(blank=True, default='', verbose_name='店铺简介'),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='shops/', verbose_name='店铺Logo'),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='店铺名称'),
        ),
    ]
