# Generated by Django 5.2.6 on 2026-06-23 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='优惠券名称')),
                ('coupon_type', models.CharField(choices=[('minus', '满减券'), ('discount', '折扣券'), ('newcomer', '新人券')], default='minus', max_length=20, verbose_name='类型')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面值/折扣')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消费')),
                ('total_count', models.IntegerField(default=100, verbose_name='发行总量')),
                ('claimed_count', models.IntegerField(default=0, verbose_name='已领取数量')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=20, verbose_name='状态')),
                ('order_no', models.CharField(blank=True, default='', max_length=64, verbose_name='使用订单号')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='marketing.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupon_records',
                'ordering': ['-claimed_at'],
            },
        ),
    ]
