# Generated by Django 6.0.6 on 2026-06-29 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponrecord',
            unique_together={('user', 'coupon')},
        ),
    ]
