# Generated by Django 5.2.6 on 2026-06-22 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.IntegerField(db_index=True, verbose_name='SKU ID')),
                ('spu_id', models.IntegerField(db_index=True, verbose_name='SPU ID')),
                ('order_no', models.CharField(default='', max_length=64, verbose_name='订单号')),
                ('rating', models.IntegerField(default=5, verbose_name='评分')),
                ('content', models.TextField(blank=True, default='', verbose_name='评价内容')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='评价图片')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名评价')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.review')),
            ],
            options={
                'db_table': 'review_replies',
            },
        ),
    ]
